-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 29 nov. 2022 à 12:05
-- Version du serveur : 10.4.25-MariaDB
-- Version de PHP : 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `api_snk`
--

-- --------------------------------------------------------

--
-- Structure de la table `personnages2`
--

CREATE TABLE `personnages2` (
  `id` int(11) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `histoire` text DEFAULT NULL,
  `affiliation` varchar(255) DEFAULT NULL,
  `origine` varchar(255) DEFAULT NULL,
  `imageCarte` varchar(255) DEFAULT NULL,
  `imageHistoire` varchar(255) DEFAULT NULL,
  `id_user` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `personnages2`
--

INSERT INTO `personnages2` (`id`, `nom`, `histoire`, `affiliation`, `origine`, `imageCarte`, `imageHistoire`, `id_user`) VALUES
(1, 'Eren Jäger', 'Eren Jäger (japonais : エレン・イェーガー, Hepburn : Eren Yēgā?) est un membre du Bataillon d\'exploration et le protagoniste, puis l\'antagoniste principal de la série. Il a vécu dans le District de Shiganshina avec ses parents et Mikasa Ackerman jusqu\'à la chute du Mur Maria. Au cours de l\'incident, Eren assiste, impuissant, à la mort de sa mère par la main d\'un Titan. Cet événement suscite chez Eren une haine intense envers les Titans, ce dernier voulant les éradiquer jusqu\'au dernier.En l\'an 847, Eren, Mikasa et Armin Arlelt, leur meilleur ami, s\'enrôlent dans la 104ème Brigade d\'entraînement. Tous les trois obtiennent leur diplôme, Eren étant à la 5ème place. Ils rejoignent le Bataillon d’exploration après la Bataille de Trost.Après la Bataille de Shiganshina, Eren et ses camarades arrivent finalement au sous-sol de sa maison natale. Eren se connecte par la suite aux souvenirs de son père, en complément aux trois carnets trouvés, et apprend la vérité sur le Monde Extérieur et les Titans. Eren promet alors de libérer les habitants des 3 Murs de leur véritable ennemi : Mahr et le reste du monde. ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/erenCarte.webp', 'http://localhost/shingeki-no-kyojin/img/erenHistoire.jpg', NULL),
(2, 'Dot Pixis', 'Dot Pixis (japonais : ドット·ピクシス, Hepburn : Dotto Pikushisu?) est un Commandant de Corps d\'Armée ainsi que le plus haut responsable militaire de défense des Territoires du Sud au sein de l\'Armée de Paradis. En effet, il est Commandant de la Garnison et dispose des pleins pouvoirs pour tout ce qui concerne la défense de l\'humanité.\nAprès la mort du Généralissime Daris Zackley, Pixis le remplace et se retrouve alors à la tête de l\'Armée. Dot Pixis est un homme âgé. Il est chauve et possède une moustache de couleur grise ainsi que des yeux dorés. Comme les autres Commandant, Pixis a un collier avec un genre de cristal autour de son cou, montrant son rang de commandant.Pixis est un personnage assez excentrique : Un jour, en observant des Titans pénétrer dans la brèche du Mur Rose, il a affirmé que cela ne le dérangerait pas d\'être mangé par un Titan, si celui-ci possédait une apparence féminine et une beauté particulière.  Il sait garder son calme, ainsi qu\'un comportement serein et léger, même au milieu du chaos.\n', 'Garnison', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/pixisCarte.webp', 'http://localhost/shingeki-no-kyojin/img/pixisHistoire.jpg\r\n', NULL),
(3, 'Falco Gleis', 'Falco Gleis (japonais : ファルコ・グライス, Hepburn : Faruko Guraisu?) est un guerrier Eldien qui travaille pour le gouvernement Mahr et est le frère cadet de Kord Gleis. Il était également un des candidats pour hériter du Titan Cuirassé. Il possède en ce moment le Titan Mâchoire. Falco est un jeune adolescent de taille moyenne pour son âge. Il est blond et a de grands yeux ambre.\n\nComme tous les Aspirants Guerriers, il porte un uniforme gris clair composé d\'une veste, d\'un pantalon, de bottes noires montantes jusqu\'au niveau des genoux ainsi qu\'une ceinture à munitions avec des bretelles. Il porte occasionnellement un casque gris foncé blindé semblable à un casque Adrian.\n\nEn tant qu\'aspirant guerrier, il porte un brassard jaune dont l\'étoile et les bords sont blancs. Il doit porter en toutes circonstances ce brassard sous peine d\'avoir des problèmes avec le commandement Mahr.  ', 'Aspirant guerrier', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/falcoCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/falcoHistoire.webp', NULL),
(4, 'Armin Arlelt', 'Armin Arlelt (japonais : アルミン・アルレルト, Hepburn : Arumin Arureruto?) est un soldat d\'élite du Bataillon d\'exploration. Il succède à Hansi Zoe au poste de major et devient le 15ème Major du Bataillon d\'exploration. Il est aussi un ami d\'enfance d\'Eren Jäger et Mikasa Ackerman, et l\'un des protagonistes principaux de la série. Bien qu\'il semble être parmi les plus faibles physiquement de la 104ème Brigade d\'entraînement, son intelligence et son génie stratégique font de lui un atout inestimable, surtout lorsqu\'il est associé à Hansi Zoe. Durant la Bataille du District de Shiganshina, il prit le pouvoir du Titan Colossal (japonais : 超大型巨人, Hepburn : Chō ōgata Kyojin?) à Bertolt Hoover.  Armin possède un visage enfantin, encadré par des cheveux blonds avec des yeux d\'un bleu profond.Armin est quelqu\'un de petit et mince. En tant que soldat, Armin porte l\'uniforme standard des troupes militaires.En tant que titan primaire, il a les cheveux blonds et mi-longs faisant penser à ceux de sa forme humaine.', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/arminCarte.gif', 'http://localhost/shingeki-no-kyojin/img/arminHistoire.jpg', NULL),
(5, 'Erwin Smith', 'Erwin Smith (japonais : エルヴィン・スミス, Hepburn : Eruvin Sumisu?) était un Commandant de Corps d\'Armée au sein de l\'Armée de Paradis. En effet, il fut le 13ème Major du Bataillon d\'exploration. Le Major Smith était un des meilleurs stratèges et faisait preuve d\'une impartialité exemplaire lorsqu\'il s\'agissait du futur de l\'humanité : il n\'hésitait jamais à sacrifier ses hommes dans ce but. Erwin était un homme assez grand avec des cheveux blonds, toujours soigneusement peignés. Il avait une carrure large et musclée et était plutôt costaud. Comme les autres Commandant, Smith avait un collier avec une sorte de cristal autour de son cou. Il perdit son bras droit lors du sauvetage d\'Eren Jäger après que celui-ci fut enlevé par Reiner Braun et Bertolt Hoover.Erwin était un homme grave, calculateur, capable de planifier sur le long terme. Alors qu\'il faisait confiance à ses hommes, il fut le premier à réaliser qu\'un espion se trouvait dans le Bataillon d\'exploration et prit les dispositions nécessaires pour sa capture. ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/erwinCarte.webp', 'http://localhost/shingeki-no-kyojin/img/erwinHistoire.jpg', NULL),
(7, 'Mikasa Ackerman', 'Mikasa Ackerman (japonais : ミカサ・アッカーマン, Hepburn : Mikasa Akkāman?) est la sœur adoptive d\'Eren Jäger, ainsi que l\'une des protagonistes principaux de la série. Après l\'assassinat de ses parents biologiques par des trafiquants d\'êtres humains, elle est sauvée par Eren et vit avec lui et ses parents, Grisha et Carla, jusqu\'à la chute du Mur Maria.\n\nBien qu\'elle désire seulement vivre paisiblement avec Eren, Mikasa choisit de le suivre au sein de l\'Armée Humaine. Lors de sa formation dans la 104ème Brigade d\'entraînement, elle excelle dans tous les domaines et est classée 1ère de sa promotion. Elle rejoint par la suite le Bataillon d\'exploration, dans le but de suivre et protéger Eren.\n\nOn apprend par la suite que Mikasa est également la dernière descendante d\'une branche du Clan Azumabito qui avait suivi Karl Fritz lors de son départ sur l\'île de Paradis. ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/mikasaCarte.webp', 'http://localhost/shingeki-no-kyojin/img/mikasaHistoire.jpg', NULL),
(8, 'Historia Reiss', 'Historia Reiss (japonais : ヒストリア・レイス, Hepburn : Hisutoria Reisu?) est la Reine actuelle de Paradis, fille illégitime de Rhodes Reiss et d\'une de ses servantes, Alma. Elle est l\'une des derniers représentants de la famille royale, avec Sieg Jäger. Durant la chute du Mur Maria, sa mère se fait assassiner, sous les directives de son père. Ce dernier la contraint de renoncer à son nom, pour celui de Christa Lenz (japonais : クリスタ・レンズ, Hepburn : Kurisuta Renzu?). Elle s\'enrôle par la suite dans l\'Armée Humaine, afin de se faire oublier des hommes de pouvoir. Elle obtient son diplôme au sein de la 104ème Brigade d\'entraînement, étant classée 10ème. De plus, elle rejoint le Bataillon d\'exploration suite aux événements de La Bataille de Trost.Elle finit par accepter son vrai nom, et se révèle être un atout conséquent durant le coup d\'état contre la capitale. Après ça, elle revendique pleinement le sang des Reiss et devient la reine légitime des 3 Murs, ainsi que d\'Eldia. Sous les traits de Christa Lenz, Historia est une fille réservée et gentille. Elle aime prêter main forte à ses camarades bien que dans certains cas, elle ne sait comment agir. ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/HistoriaCarte.png', 'http://localhost/shingeki-no-kyojin/img/historiaHistoire.jpg', NULL),
(11, 'Bertolt Hoover', 'Bertolt Hoover (japonais : ベルトルト・フーバー, Hepburn : Berutoruto Fūbā?) était un Eldien sous les ordres de l\'Empire Mahr. Après s\'être qualifié pour devenir l\'un des Guerriers de Mahr, il hérita du Titan Colossal (japonais : 超大型巨人, Hepburn : Chō-ōgata Kyojin?). En l\'an 845, accompagnant Reiner Braun, Annie Leonhart et Marcel Galliard, il usa de son pouvoir afin de briser le Mur Maria, début d\'une vaste opération servant le but de récupérer le Titan Originel.Afin de mieux infiltrer Paradis, il s\'engagea dans la 104ème Brigade d\'entraînement et décrocha la 3ème place.Ayant repéré un potentiel détenteur du Titan Originel, Eren Jäger, il intégra par la suite le Bataillon d\'exploration, accompagné de Reiner, pour s\'assurer de la véracité de leurs soupçons.Bertolt était un jeune homme mince, plutôt grand. Il est l\'un des plus grands personnages de la série. Il avait les cheveux noirs courts, les yeux de la même couleur, les sourcils minces et un visage allongé. Dans l\'anime, ses yeux sont verts et il a un teint légèrement plus foncé. Il était vu principalement dans l\'uniforme standard du Bataillon d\'Exploration. Suite à sa rencontre avec Sieg Jäger, ses cheveux semblèrent plus courts. ', 'Aspirant Guerrier', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/bertoltCarte.webp', 'http://localhost/shingeki-no-kyojin/img/bertoltHistoire.webp', NULL),
(12, 'Marcel Galliard', 'Marcel Galliard (japonais : マルセル・ガリアード, Hepburn : Maruseru Gariādo?) était le frère de Porco Galliard ainsi que l\'un des Guerriers de Mahr. En l\'an 845, il fut sélectionné pour participer à une opération aux enjeux importants, dérober le Titan Originel des mains de Paradis. Cependant, il fut, avant d\'arriver à destination, dévoré par Ymir sous sa forme de Titan Primaire, cette dernière lui volant son pouvoir, le Titan Mâchoire (japonais : 顎の巨人, Hepburn : Agito no Kyojin?). Lorsqu\'il était enfant, Marcel s\'enrôla dans l\'armée de Mahr. Il suivit un entraînement militaire ardu visant à former les futurs guerriers et fut remarqué pour ses capacités physiques. Avec Reiner Braun, Bertolt Hoover et Annie Leonhart, il fut choisi pour participer à la mission d\'infiltration de Paradis et hérita du Titan Mâchoire. ', 'Aspirant Guerrier', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/marcelCarte.webp', 'http://localhost/shingeki-no-kyojin/img/marcelHistoire.jpg', NULL),
(13, 'Conny Springer', 'Conny Springer (japonais : コニー・スプリンガー, Hepburn : Konī Supuringā?) est l\'un des personnages secondaires de la série L\'Attaque des Titans. Il est l\'un des personnages ayant fait partie de la 104ème Brigade d\'entraînement où il a été classé 8ème au terme de la formation de Keith Shardiz. Il a par la suite, rejoint le Bataillon d\'Exploration.Conny est très émotif et ne sait pas cacher ses sentiments. Même dans le pire des scénarios, il essaie toujours de faire le «gars tout pompé».\n\nCe personnage qu\'est Conny est désireux de combattre les Titans et par conséquent ne craint pas d\'être tué par l\'un des leurs. L\'une de ses faiblesses et qui lui fait cruellement défaut est le fait de ne pas être un brillant soldat.Il a tendance à se jeter des fleurs, se désignant souvent comme un génie. Il est un petit peu railleur, se moquant par exemple d’Eren lorsqu’il rate son exercice. Il reste néanmoins gentil et sensible, paraissant profondément tourmenté lorsqu’il pense les habitants de son village morts (qui l’avait pourtant raillé auparavant pour son désir de devenir soldat malgré son petit gabarit). ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/connyCarte.webp', 'http://localhost/shingeki-no-kyojin/img/connyHistoire.jpg', NULL),
(14, 'Hansi Zoe', 'Hansi Zoe (japonais : ハンジ・ゾエ, Hepburn : Hanji Zoe?) était le 14ème Major du Bataillon d\'exploration.Elle fut Capitaine de sa propre Escouade du Bataillon d\'exploration au même titre que Mike Zacharias.Au sein du Bataillon, Hansi menait des recherches sur les Titans au point d\'être obsédée par eux. En raison de cela, elle était profondément intéressée par Eren Jäger et sa capacité à se transformer en Titan Assaillant.Elle perdit la vie en 854 lors du Grand Terrassement en se sacrifiant pour permettre à l\'Alliance Bataillon d\'exploration - Unité des Guerriers de quitter la ville d\'Odiha. Hansi est très passionnée par ce qu\'elle fait et s’investit énormément. Elle est clairement hyperactive et adore discuter de ses projets avec les autres personnes. Hansi est aussi extrêmement intéressée par les Titans au point d\'en devenir obsessionnelle, voire à la limite de la folie. À chaque fois que le Bataillon d\'exploration part en expédition, elle est l\'une des rares à être toute excitée à l\'idée de rencontrer des Titans.', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/hansiCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/hansiHistoire.jpg', NULL),
(15, 'Livaï Ackerman', 'Livaï Ackerman (japonais : リヴァイ・アッカーマン, Hepburn : Rivai Akkāman.?), souvent designé comme le Caporal-Chef Livaï (リヴァイ兵長 Rivai Heichō), est le Capitaine (兵士長 Heishichō) de l\'Escouade tactique au sein du Bataillon d\'exploration. Il est connu pour être le soldat le plus puissant de l\'Armée de Paradis.Livaï possède des cheveux châtains foncés mi-longs et rasés sur les côtés. Il possède d’intimidants yeux gris foncé. Malgré sa petite taille, il a un physique très développé. Mis à part son froncement de sourcils presque constant, l\'expression de son visage est neutre, on peut le voir sourire rarement.Son attitude imperturbable rend difficile de deviner ce à quoi il pense. Que ce soit en civil ou en uniforme, Livaï est toujours vu arborant un foulard blanc noué autour du cou. Parfois, il porte un chandail moulant à manches longues ainsi qu\'un costume.', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/livaïCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/livaïHistoire.jpg', NULL),
(16, 'Sasha Braus', 'Sasha Braus (japonais : サシャ・ブラウス, Hepburn : Sasha Burausu?) était une diplômée de la 104ème Brigade d\'entraînement, en laquelle elle s\'était hissée à la 9ème place. Elle avait, par la suite, décidé de rejoindre le Bataillon d\'exploration. Elle était également l\'une des rares survivantes de la Bataille de Shiganshina, la quasi-totalité des effectifs du bataillon ayant été décimés par leurs opposants. Elle perd cependant la vie lors de la Bataille de Revelio, tuée par Gaby Braun.Sasha est une jeune fille plutôt grande et mince. Elle a de longs cheveux épais de couleur brune, attachés en queue de cheval, avec quelques mèches sur le devant du visage et une frange vers la gauche. Ses yeux, d\'un brun doré dans l\'anime, sont également légèrement cernés et elle a un regard mature et déterminé avec une bouche mince et affinée.  ', 'Bataillon d\'exploration', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/sashaCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/sashaHistoire.jpg', NULL),
(17, 'Gaby Braun', 'Gaby Braun (japonais : ガビ・ブラウン, Hepburn : Gabi Buraun?) est une jeune Eldienne du continent enrôlée dans l\'armée de Mahr. Elle est une candidate pour hériter du pouvoir du Titan Cuirassé.Gaby est une pré-adolescente de taille moyenne avec des grands yeux noisettes et des sourcils plutôt épais. Ses cheveux foncés, mi-longs, sont attachés en une couette arrière.Lors de la Bataille de la Forteresse de Slava et des entraînements militaires, elle porte l\'uniforme réservé aux Eldiens, sans oublier le Brassard eldien jaune, signe de son appartenance au peuple Eldien et de son statut d\'Aspirante Guerrière. Gaby est une adolescente particulièrement arrogante et égocentrique. Elle n\'hésite pas à s\'autocongratuler à outrance lors de ses réussites. En résulte une sensation de supériorité vis-à-vis de ses camarades aspirants guerriers. Elle est aussi une jeune fille à la détermination inébranlable, et elle est capable de tout pour parvenir à ses fins.', 'Aspirante Guerrière', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/gabyCarte.webp', 'http://localhost/shingeki-no-kyojin/img/gabyHistoire.jpg', NULL),
(18, 'Peak Finger', 'Peak Finger (japonais : ピーク・フィンガー, Hepburn : Pīku Fingā?) est une guerrière Eldienne de l\'Empire Mahr et l\'actuelle détentrice du Titan Charrette (japonais : 車力の巨人, Hepburn : Shariki no Kyojin?).Elle est très intelligente, capable de déduire rapidement une situation. Sa sagacité a été déterminante pour l\'obtention de son titan. Lorsque les guerriers discutent de la perspective d\'utiliser le Clan Teyber pour aider à leurs opérations, Peak a pu rapidement comprendre les choses, et Sieg Jäger montre que cela a l\'air d\'arriver assez souvent.Peak se montre gentille et préoccupée par ses compagnons de guerre et les cadets guerriers. Parfois cela peut la rendre un peu naïve comme pendant le trajet en train vers Revelio, Peak a donné à Kord Gleis une bouteille d\'alcool car il avait soif, pensant bien faire ce qui montre sa gentillesse. Cependant, cela a amené Kord à boire et à conduire les autres soldats Eldiens à chanter en faveur de Gaby.', 'Aspirante Guerrière', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/peakCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/peakHistoire.jpeg', NULL),
(19, 'Theo Magath', 'Theo Magath (japonais : テオ・マガト, Hepburn : Teo Magato?) est le dernier Maréchal en titre de l\'Armée de Mahr. Il était autrefois un des instructeurs chargés de l\'encadrement des guerriers avant de devenir Commandant terrestre d\'unité Eldienne avant d\'enfin prendre la tête de l\'armée, suite à la mort de Calvi.Magath était une personne qui savait garder son calme dans les situations les plus épineuses.Dans un premier temps, comme beaucoup de Mahrs, il considérait les Eldiens comme des êtres inférieurs. Il traitait les soldats issus de cette ethnie comme de la chair à canon. Malgré cela, il ne les maltraitait jamais physiquement et reconnaissait les qualités de certains, étant prêt à sacrifier 800 soldats Eldiens pour protéger les guerriers et les Titans primordiaux, soldats Eldiens d\'exception, de l\'ennemi. Plus particulièrement, il reconnaissait le talent de Gaby et l\'autorisa même à enlever son brassard pour une opération, et avait confiance en Sieg, qu\'il connaissait depuis vingt ans. ', 'Maréchal', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/theoCarte.webp', 'http://localhost/shingeki-no-kyojin/img/theoHistoire.jpg', NULL),
(21, 'Willy Teyber', 'Willy Teyber(japonais : ヴィリー・タイバー, Hepburn : Virī Taibā?) était un noble eldien vivant dans l\'opulence à Mahr. Il faisait partie du Clan Teyber. Il confia à Theo Magath que sa famille contrôlait l\'Empire Mahr.Il périt lors de l\'attaque d\'Eren Jäger, dévoré par la forme titanesque du Titan Assaillant, ce dernier l\'ayant éventré au niveau du ventre.Willy était le gendre idéal : brillant diplomate, homme du monde spirituel, charismatique, charmeur, ayant cultivé les amitiés avec de nombreuses diplomates de premier plan.\nEn réalité, derrière cet apparence vivait un autre Willy beaucoup moins sympathique. Un politicien retord prêt à offrir froidement une foule sur un plateau, comprenant ses amis, sachant bien qu\'un attentat aurait lieu lors de son discours mais laissant faire pour voir son ambition de provoquer une invasion internationale contre l\'île de Paradis pour permettre à Mahr de mettre la main sur le Titan Originel se réaliser.', 'Dirigeant officieux de Mahr', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/willyCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/willyHistoire.jpg', NULL),
(22, 'Sieg Jäger', 'Sieg Jäger (japonais : ジーク・イェーガー, Hepburn : Jīku Yēgā?) est le capitaine de l\'Unité des Guerriers de Mahr, chargée de dérober le Titan Originel des mains de Paradis. Il est le détenteur actuel du Titan Bestial (japonais : 獣の巨人, Hepburn : Kemono no Kyojin?), et est considéré par Reiner Braun comme le Guerrier le plus puissant de l\'armée Mahr, en contraste avec Livaï Ackerman qui serait le soldat le plus puissant de l\'île de Paradis. Sieg est le fils de Grisha Jäger et Dinah Fritz, le demi-frère aîné d\'Eren Jäger, et un membre de la Famille Royale de par sa mère.Sieg Jäger est un homme intelligent et stratégique. Cependant il ne réfléchit pas à ses mots avant de parler, mais ose dire la vérité et ce qu\'il pense. Il lui arrive souvent d\'avoir des manières euphoriques ou de faire du sarcasme. Sieg ne fait pas dans le sentiment et semble alors difficilement éprouver de la pitié pour les autres, même envers des enfants. Il trouve même de l\'amusement lorsqu\'il s\'agit de lapider des ennemis, considérant le combat comme un match de baseball. ', 'Aspirant Guerrier', 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/siegCarte.webp', 'http://localhost/shingeki-no-kyojin/img/siegHistoire.webp', NULL),
(23, 'Ymir', 'Ymir (japonais : ユミル, Hepburn : Yumiru?) était une diplômée de la 104ème Brigade d\'entraînement ainsi qu\'une ancienne membre du Bataillon d\'exploration. Elle possédait la capacité de se transformer en Titan Mâchoire (japonais : 顎の巨人, Hepburn : Agito no Kyojin?), et avait des connaissances concernant la vraie nature des Titans ainsi que l\'histoire du Monde Extérieur. Au premier abord, Ymir semble très indifférente aux autres, le genre de personne égocentrique, cynique et se montrant arrogante face à ses camarades. On découvre par la suite qu\'elle peut être très attachante et attentionnée avec ses proches, notamment à travers sa relation avec Historia Reiss (Christa Lenz). Enfant, Ymir fut recueillie par une personne encore inconnue qui s\'apparenterait à un homme d\'église. Après que cet homme et son acolyte l\'eurent choisie parmi d\'autres orphelins, ils l\'amenèrent dans une sorte de chapelle peu fréquentée où elle fut présentée comme une descendante de la famille royale, bien qu\'elle n\'eût aucun lien de parenté quelconque avec cette dernière. Ses adorateurs lui vouaient un culte jusqu\'au jour où elle fut arrêtée ainsi que les personnes qui croyaient en ce mensonge, par des soldats Mahrs. ', NULL, 'Eldiens', 'http://localhost/shingeki-no-kyojin/img/ymirCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/ymirHistoire.png', NULL),
(24, 'Titan Assaillant', 'Le Titan Assaillant (japonais : 進撃の巨人, Hepburn : Shingeki no Kyojin?) est un Titan Primordial connu pour avoir toujours combattu pour la liberté d\'Eldia. Il possède la capacité de transmettre des souvenirs aux anciens possesseurs, comme démontré par son détenteur actuel, Eren Jäger.Le Titan Assaillant a un comportement excessif/rageur envers les Titans, puisqu\'il cherche en effet à en tuer le plus possible. Ce comportement, d\'abord attribué à la colère de l\'Humanité par Mikasa, est en fait calqué sur la mentalité d\'Eren, son \"hôte\", qui déteste les titans. Il est à noter aussi que le pouvoir du Titan Assaillant est porté pour délivrer le royaume d\'Eldia.Dans l\'Arc du Choc des Titans, il est capable de soulever le Titan Cuirassé et de le vaincre. Il est également capable, probablement dans un état de colère et de rage, de pouvoir enflammer son corps. À ce moment-là, ses yeux deviennent bleus et sa puissance est décuplée. Il a fait cela une seule fois dans la série, pour vaincre Annie. On dit alors que ce titan est sous la forme Berserker, forme qui est exclusive à l\'anime. Il n\'est, à ce jour, pas révélé s\'il s\'agit d\'une capacité spéciale du Titan Assaillant ou d\'une \"surchauffe\" de son corps utilisant ses attributs plus efficacement.  ', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanCarte.webp', 'http://localhost/shingeki-no-kyojin/img/titanHistoire.jpg', NULL),
(25, 'Titan Colossal', 'Le Titan Colossal (japonais : 超大型巨人, Hepburn : Chō-ōgata Kyojin?) est un Titan Primordial notable pour sa taille nettement supérieure aux autres Titans et son contrôle important sur la vapeur émise par son corps. Il est actuellement en possession d\'Armin Arlelt.Le Titan colossal est apparu pour la première fois, dans l\'épisode 1 de l\'Anime ou le Chapitre 1 du manga, face aux humains terrorisés par sa main gigantesque, puis par sa tête dépourvue de peau qui apparut peu après au dessus du mur (faisant pourtant 50 mètres de haut). Il fit une brèche dans le Mur Maria en donnant un coup de pied gigantesque, laissant ainsi les autres Titans entrer à l\'intérieur des murs et provoquant la chute du District de Shiganshina.Il apparaît aussi une deuxième fois dans le District de Trost, devant le mur de Trost, et détruit la porte et les canons avant de se volatiliser aussi soudainement que la première fois. On le voit aussi durant l\'Arc du Choc des Titans. D\'abord sous sa forme humaine, il se transforme en même temps que le Titan Cuirassé. Cependant, il ne se transforme qu\'en Titan incomplet car sa transformation est incomplète et seulement la moitié supérieure de son corps apparaît.', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanColossalCarte.webp', 'http://localhost/shingeki-no-kyojin/img/titanColossalHistoire.jpg', NULL),
(26, 'Titan Mâchoire', 'Le Titan de Porco Galliard, le Titan Mâchoire, a un regard perçant et des yeux brun extrêmement clairs entourés de chair béante le tout lui donnant un air féroce. L\'ensemble est surplombé par des arcades sourcilières proéminentes. Comme son nom le laisse entendre sa mâchoire représente une partie importante de sa physionomie.\n\n    Elle est très développée et est recouverte d\'un blindage qui monte jusqu\'à sa lèvre inférieure. Il porte également une barbe qui recouvre son menton et le reste de sa mâchoire. L\'ouverture de sa bouche est partiellement recouverte par le blindage qui dessine une rangée de dents crénelées. Quant à ses cheveux, ils sont longs et de même couleur que sa barbe à savoir clairs.Lorsqu\'il est en possession d\'Ymir, le Titan Mâchoire a des cheveux noirs, longs et des dents très pointues. Ses yeux semblent plus petits que ceux des autres titans.\n', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanMâchoireCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/titanMâchoireHistoire.jpg', NULL),
(27, 'Titans du Mur', 'Les Titans du Mur sont un type inhabituel de Titans qui composent les murs et protègent l\'humanité. Ils ont d\'abord été révélés lorsque le Titan Féminin avait essayé de monter sur le Mur Sina pour échapper au Bataillon d\'exploration. Le manque de lumière du soleil à l’intérieur des murs les rend immobiles. \n\n      Les Titans du Mur sont enveloppés de mystères. Rien sur leur histoire n\'est encore connu à ce jour. Des questions comme : « D\'où viennent-ils ? » et « Quelles sont leurs motivations ? », sont encore sans réponses.Les Titans du Mur sont semblables en apparence au Titan Colossal, car la surface de leur corps est principalement recouverte de tissus musculaires et de part leur taille gigantesque. Leur hauteur exacte n\'est pas connue, mais vu qu\'ils constituent les Murs, ils doivent être extrêmement grands (environ 50 mètres de haut peut être moins).', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanDuMurCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/titanDuMurHistoire.webp', NULL),
(28, 'Titan Bestial', 'Le Titan Bestial (japonais : 獣の巨人, Hepburn : Kemono no Kyojin?) est un Titan Primordial ayant un aspect animal unique et étant légèrement plus grand que la plupart des Titans.Le Titan Bestial survient la première fois avec les autres Titans apparus dans l\'enceinte du Mur Rose, dans l\'Arc du Choc des Titans (qui correspond à la Saison 2 de l\'anime) . Il saisit alors le cheval de Mike Zacharias et lui lance dessus, et cherche ensuite à en savoir plus sur le Dispositif de Manœuvre Tridimensionnelle auprès de ce dernier, mais comme il ne répondit pas, il ordonna aux autres Titans de le dévorer. Il sera aperçu plus tard, près de la Forteresse d\'Utgarde se dirigeant vers le Mur Rose afin de l\'escalader. Une fois en haut du Mur, il rugira et d\'autres Titans arriveront, se dirigeant quant à eux vers la Forteresse. Après cela, il disparaîtra derrière le Mur Rose.Pendant que l\'opération visant à capturer Annie Leonhart, alors soupçonnée d\'être le Titan Féminin est en cours, les membres suspectés d\'être des complices d\'Annie au sein de la 104ème Brigade d\'entraînement sont sous la surveillance rapprochée du Bataillon d\'exploration.', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanBestialCarte.webp', 'http://localhost/shingeki-no-kyojin/img/titanBestialHistoire.jpg', NULL),
(29, 'Titan Cuirassé', 'Le Titan Cuirassé (japonais : 鎧の巨人, Hepburn : Yoroi no Kyojin?) est un Titan Primordial possédant des plaques de peau blindées sur son corps. Il est actuellement en possession de Reiner Braun, mais il est convoité par sa cousine Gaby ainsi que Falco avant d\'obtenir le Titan Mâchoire.Alors que le territoire des humains fut envahi par les Titans, le Titan Cuirassé apparut. Dès sa première apparition, on le voit foncer sur la porte qui était en train de se fermer afin de protéger l\'Humanité. Le Titan Cuirassé détruisit le mur sous le regard horrifié des humains. Une flamme sortit alors de sa bouche.Reiner Braun révèle à Eren qu\'il est le Titan Cuirassé et que Bertolt est le Titan Colossal. Puis il se transforme en Titan, prend Eren dans sa main et descend du Mur Rose.La caractéristique déterminante du Titan Cuirassé est la multitude de plaques de peau blindées plaquées protégeant son corps à la manière d\'une armure. Cette armure est capable de le protéger de dommages importants, même d\'un coup direct d\'un canon ou des lames en acier renforcé de l\'Équipement Tridimensionnel.', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanCuirasséCarte.jpg\r\n', 'http://localhost/shingeki-no-kyojin/img/titanCuirasséHistoire.gif\r\n', NULL),
(30, 'Titan Marteau d\'Armes', 'Le Titan Marteau d\'Armes (japonais : 戦槌の巨人, Hepburn : Sentsuchi no Kyojin?) est un Titan Primordial ayant la capacité de se servir du Durcissement afin créer des structures massives. Il a été en possession du Clan Teyber pendant des générations jusqu\'à ce qu\'il soit dérobé par Eren Jäger après qu\'il ait dévoré Lara Teyber.Le Titan Marteau d\'Armes peut utiliser le Durcissement pour produire et manipuler des structures pouvant être militarisées de plusieurs façons. Cette capacité peut également créer des armes flexibles, comme la corde d\'une arbalète ou les lanières d\'un fouet. Tout comme avec le Titan Féminin, ce Durcissement peut également être utilisé pour enfermer son corps d\'être humain dans un \"noyau durci\".Le cristal et le corps titanesque sont reliés par un long cordon. Lorsque cette capacité est utilisée, le corps du Titan Marteau d\'Armes est généré partant des pieds vers le haut plutôt que de la nuque à l\'extérieur. ', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanMarteauCarte.png\r\n', 'http://localhost/shingeki-no-kyojin/img/titanMarteauDarmesHistoire.jpg\r\n', NULL),
(31, 'Titan Charette', 'Le Titan Charrette (japonais : 車力の巨人, Hepburn : Shariki no Kyojin?) est un Titan Primordial ayant une forme quadrupède, ainsi qu\'une vitesse et une endurance dévastatrices. Il est actuellement détenu par Peak.Après que le Titan Bestial et son armée se soient transformés, le Titan Charrette peut être aperçu parmi eux en train de porter des caisses ainsi que des tonneaux dans son dos. Lorsqu\'Erwin Smith vit ceci, il crut d\'abord que le Titan n\'était pas avec le reste de l\'armée. L\'ancien major en vint ensuite à l\'hypothèse que le Titan était intelligent et agissait comme un éclaireur pour prévenir Reiner Braun de leur approche.Le Titan Charrette possède un niveau d\'endurance supérieur à celui des autres Titans Primordiaux, permettant ainsi à ses détenteurs de participer à des missions de longue durée, pouvant durer jusqu\'à plusieurs mois, sans avoir besoin de reprendre forme humaine[1][2]. Sa résistance à la fatigue lui permet de conserver sa forme de Titan pendant de longues périodes et de porter de nombreux armements tels que des armures de combat, des mitrailleuses mobiles et des packs de fret pour diverses tactiques telles que le nettoyage des tranchées et des opérations à long terme en territoire ennemi.', NULL, 'Titans', 'http://localhost/shingeki-no-kyojin/img/titanCharetteCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/titanCharetteHistoire.webp', NULL),
(33, 'Annie Leonhart', 'Annie Leonhart (japonais : アニ・レオンハート, Hepburn : Ani Reonhāto?) est une diplômée de la 104ème Brigade d\'entraînement ainsi qu\'une ancienne membre des Brigades spéciales. Ses compétences remarquables dans le maniement de la lame et le combat au corps-à-corps lui ont d\'ailleurs valu la 4ème place. Elle possède la capacité de se transformer en Titan Féminin (japonais : 女型の巨人, Hepburn : Megata no Kyojin?). Entraînée dès son plus jeune âge par son père, elle fut sélectionnée afin de devenir une Guerrière de l\'Empire Mahr. En l\'an 845, elle fut envoyée en mission visant à récupérer le Titan Originel des mains de Paradis. Elle était accompagnée de Reiner Braun, Bertolt Hoover et Marcel Galliard. En tant que Titan Féminin, elle sert d\'antagoniste majeur avant sa défaite, durant laquelle elle s\'enferma dans un solide cristal, tout en se plongeant dans le coma. Retenue prisonnière du cristal durant 4 années sous la garde du Brigades Spéciales, elle est actuellement enfin libre indirectement grâce à Eren. ', 'Garnison spéciales', 'Mahr', 'http://localhost/shingeki-no-kyojin/img/annieCarte.jpg', 'http://localhost/shingeki-no-kyojin/img/annieHistoire.Webp', 1);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `personnages2`
--
ALTER TABLE `personnages2`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personnages_nom_unique` (`nom`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `personnages2`
--
ALTER TABLE `personnages2`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=131;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
